version: '3.4'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
     - '3300:3306'
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=LN
      - MARIADB_ROOT_USER=ligth
      - MARIADB_ROOT_PASSWORD=pwd123
    volumes:
      - 'mariadb_data:/bitnami'
#  postfix:
#    container_name: getLn-postfix
#    image: tozd/postfix
#    environment:
#      - MY_NETWORKS=172.18.0.0/16 172.20.0.0/16 127.0.0.0/8
#    ports:
#      - "26:25"
#      - "465:465"
#      - "587:587"
volumes:
  mariadb_data:
    driver: local

