version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
     - '3300:3306'
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=LN
      - MARIADB_ROOT_USER=ligth
      - MARIADB_ROOT_PASSWORD=pwd123
    volumes:
      - 'mariadb_data:/bitnami'
  postfix:
    container_name: getLn-postfix
    image: tozd/postfix

volumes:
  mariadb_data:
    driver: local

