version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
     - '3300:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=root
    volumes:
      - 'mariadb_data:/bitnami'
volumes:
  mariadb_data:
    driver: local

