scheduled.getln.task: 0 */5 * * * ?
spring:
  application:
    name: Get light Novel
  datasource:
    url: jdbc:mariadb://localhost:3300/LN
    username: ligth
    password: pwd123
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.mariadb.jdbc.Driver
server:
  port: 9666

