scheduled.getln.task: * */5 * * * ?
spring:
  application:
    name: Get light Novel
  datasource:
    username: ligh
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.16:3300/LN?useUnicode=yes&characterEncoding=UTF-8
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: false

