spring:
  application:
    name: Get light Novel
  client:
    id: "test"
    #test2
    secret: "$2a$10$1OindcsE8qZXrwndTBPM4.QMNxqy0bHzHaEAvBmBosdjCDqwr0MTC"
  datasource:
    url: jdbc:mariadb://localhost:3300/LN
    username: ligth
    password: pwd123
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.mariadb.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.connectiontimeout: 50000
    properties.mail.smtp.timeout: 30000
    properties.mail.smtp.writetimeout: 50000
    password: haypjonwxdrilbwa
    username: storytoreader@gmail.com
#    test-connection: true
#    properties:
server:
  port: 9666

cron.task:
  getln:  0 */5 * * * ?
  newsMangaDoom :  0 0 8,13,17,21 * * ?
logging:
  level:
    ROOT: INFO
